// <auto-generated />
using System;
using CleanCity.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanCity.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260221210612_UpdateInitialCreateDateNull")]
    partial class UpdateInitialCreateDateNull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanCity.Domain.Entities.AIAnalysisResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ConfidencePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsGarbageDetected")
                        .HasColumnType("bit");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportId")
                        .IsUnique();

                    b.ToTable("AIAnalysisResults");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.AnonymousDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceIdentifier")
                        .IsUnique();

                    b.ToTable("AnonymousDevices");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("MaxLat")
                        .HasColumnType("float");

                    b.Property<double>("MaxLng")
                        .HasColumnType("float");

                    b.Property<double>("MinLat")
                        .HasColumnType("float");

                    b.Property<double>("MinLng")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.AwarenessContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("AwarenessContents");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.DeviceToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("DeviceTokens");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TruckId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.FileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<int?>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AIAnalysisResultId")
                        .HasColumnType("int");

                    b.Property<int?>("AwarenessContentId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeepLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ReportAssignmentId")
                        .HasColumnType("int");

                    b.Property<int?>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AIAnalysisResultId");

                    b.HasIndex("AwarenessContentId");

                    b.HasIndex("ReportAssignmentId");

                    b.HasIndex("ReportId");

                    b.ToTable("Notifications", t =>
                        {
                            t.HasCheckConstraint("CK_Notification_ExactlyOneSource", "(\r\n                        (CASE WHEN ReportId IS NOT NULL THEN 1 ELSE 0 END) +\r\n                        (CASE WHEN ReportAssignmentId IS NOT NULL THEN 1 ELSE 0 END) +\r\n                        (CASE WHEN AwarenessContentId IS NOT NULL THEN 1 ELSE 0 END) +\r\n                        (CASE WHEN AIAnalysisResultId IS NOT NULL THEN 1 ELSE 0 END)\r\n                      ) <= 1");
                        });
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.NotificationRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnonymousDeviceId")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceTokenId")
                        .HasColumnType("int");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnonymousDeviceId");

                    b.HasIndex("DeviceTokenId");

                    b.HasIndex("DriverId");

                    b.HasIndex("NotificationId", "IsRead");

                    b.ToTable("NotificationRecipients", t =>
                        {
                            t.HasCheckConstraint("CK_NotificationRecipient_ExactlyOneTarget", "(\r\n                        (CASE WHEN AnonymousDeviceId IS NOT NULL THEN 1 ELSE 0 END) +\r\n                        (CASE WHEN DriverId IS NOT NULL THEN 1 ELSE 0 END) +\r\n                        (CASE WHEN DeviceTokenId IS NOT NULL THEN 1 ELSE 0 END) +\r\n                        (CASE WHEN UserId IS NOT NULL AND LTRIM(RTRIM(UserId)) <> '' THEN 1 ELSE 0 END)\r\n                      ) = 1");
                        });
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnonymousDeviceId")
                        .HasColumnType("int");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentDriverId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnonymousDeviceId");

                    b.HasIndex("AreaId");

                    b.HasIndex("CurrentDriverId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.ReportAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActionAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId", "AssignedAt");

                    b.HasIndex("ReportId", "AssignedAt");

                    b.ToTable("ReportAssignments");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.ReportStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int>("OldStatus")
                        .HasColumnType("int");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId", "UpdatedAt");

                    b.ToTable("ReportStatusHistories");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.SewageServiceProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SewageServiceProviders");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TruckTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId")
                        .IsUnique()
                        .HasFilter("[DriverId] IS NOT NULL");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("TruckTypeId");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.TruckType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TruckTypes");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.AIAnalysisResult", b =>
                {
                    b.HasOne("CleanCity.Domain.Entities.Report", "Report")
                        .WithOne("AIAnalysisResult")
                        .HasForeignKey("CleanCity.Domain.Entities.AIAnalysisResult", "ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.Driver", b =>
                {
                    b.HasOne("CleanCity.Domain.Entities.Area", "Area")
                        .WithMany("Drivers")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Area");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.FileEntity", b =>
                {
                    b.HasOne("CleanCity.Domain.Entities.Report", "Report")
                        .WithMany("Files")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Report");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.Notification", b =>
                {
                    b.HasOne("CleanCity.Domain.Entities.AIAnalysisResult", "AIAnalysisResult")
                        .WithMany()
                        .HasForeignKey("AIAnalysisResultId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CleanCity.Domain.Entities.AwarenessContent", "AwarenessContent")
                        .WithMany()
                        .HasForeignKey("AwarenessContentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CleanCity.Domain.Entities.ReportAssignment", "ReportAssignment")
                        .WithMany()
                        .HasForeignKey("ReportAssignmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CleanCity.Domain.Entities.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AIAnalysisResult");

                    b.Navigation("AwarenessContent");

                    b.Navigation("Report");

                    b.Navigation("ReportAssignment");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.NotificationRecipient", b =>
                {
                    b.HasOne("CleanCity.Domain.Entities.AnonymousDevice", "AnonymousDevice")
                        .WithMany()
                        .HasForeignKey("AnonymousDeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CleanCity.Domain.Entities.DeviceToken", "DeviceToken")
                        .WithMany()
                        .HasForeignKey("DeviceTokenId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CleanCity.Domain.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CleanCity.Domain.Entities.Notification", "Notification")
                        .WithMany("Recipients")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnonymousDevice");

                    b.Navigation("DeviceToken");

                    b.Navigation("Driver");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.Report", b =>
                {
                    b.HasOne("CleanCity.Domain.Entities.AnonymousDevice", "AnonymousDevice")
                        .WithMany("Reports")
                        .HasForeignKey("AnonymousDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanCity.Domain.Entities.Area", "Area")
                        .WithMany("Reports")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CleanCity.Domain.Entities.Driver", "CurrentDriver")
                        .WithMany("CurrentReports")
                        .HasForeignKey("CurrentDriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AnonymousDevice");

                    b.Navigation("Area");

                    b.Navigation("CurrentDriver");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.ReportAssignment", b =>
                {
                    b.HasOne("CleanCity.Domain.Entities.Driver", "Driver")
                        .WithMany("Assignments")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanCity.Domain.Entities.Report", "Report")
                        .WithMany("Assignments")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.ReportStatusHistory", b =>
                {
                    b.HasOne("CleanCity.Domain.Entities.Report", "Report")
                        .WithMany("StatusHistories")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.Truck", b =>
                {
                    b.HasOne("CleanCity.Domain.Entities.Driver", "Driver")
                        .WithOne("Truck")
                        .HasForeignKey("CleanCity.Domain.Entities.Truck", "DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CleanCity.Domain.Entities.TruckType", "TruckType")
                        .WithMany()
                        .HasForeignKey("TruckTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Driver");

                    b.Navigation("TruckType");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.AnonymousDevice", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.Area", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.Driver", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("CurrentReports");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.Notification", b =>
                {
                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("CleanCity.Domain.Entities.Report", b =>
                {
                    b.Navigation("AIAnalysisResult");

                    b.Navigation("Assignments");

                    b.Navigation("Files");

                    b.Navigation("StatusHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
