name: cleancityapp
description: "Clean City Graduation Project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.2

  # State Management + DI
  flutter_bloc: ^9.1.0
  equatable: ^2.0.8
  get_it: ^8.0.3
  intl: ^0.19.0

  # Persistence + Network
  shared_preferences: ^2.3.0
  connectivity_plus: ^6.0.5
  http: ^1.2.2
  dio: ^5.7.0

  # Location + Maps
  geolocator: ^13.0.2
  google_maps_flutter: ^2.9.0

  # Media
  image_picker: ^1.1.2
  url_launcher: ^6.3.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3

  # Utils
  uuid: ^4.5.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
        - asset: fonts/Cairo-Bold.ttf
          weight: 700